version: "3" 
services:
    minio: # Data storage container 
        image: minio/minio:latest # Pull from dockerhub
        container_name: minio-map
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001'
    redis1: # The "job board" container
        image: redis:latest # Pull from dockerhub
        container_name: redis1
        expose: 
            - "6379"
        ports: 
            - "6379:6379"
    portal-app: # The shiny application to rule them all 
        image: portalapp:1.0 # Build 
        container_name: portalapp1
        volumes:
            - "./cfg/minio_config_compose.yml:/srv/shiny-server/cfg/minio_config_compose.yml" # App needs to connect to minio
        ports:
            - "8300:8300"
        environment:
            - SHINYPROXY_USERNAME=test_user # Required to create folder in minio
    filterdata-app: # Demo container for filtering and plotting the iris dataset
        image: filterdata:1.0 # Build 
        container_name: filterdata1
        volumes:
            - "./cfg/minio_config_compose.yml:/srv/shiny-server/cfg/minio_config_compose.yml" # App needs to connect to minio
            - "./cfg/redis_config.yml:/redis_config.yml" # App needs to connect to redis
        ports:
            - "4200:4200"
        environment:
            - SHINYPROXY_USERNAME=test_user # Required to create folder in minio
    filterdata-service:
        image: filterdata-svc:1.0 # Build 
        container_name: filterservice1
        volumes:
            - "./cfg/minio_config_compose.yml:/minio_config_compose.yml" # Service needs to connect to minio
            - "./cfg/redis_config.yml:/redis_config.yml" # Service needs to connect to redis
        ports:
            - "5601:3838"


