version: "3" 
services:
    minio: # Data storage container 
        image: minio/minio:latest # Pull from dockerhub
        container_name: minio-map
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001'
    redis1: # The "job board" container
        image: redis:latest # Pull from dockerhub
        container_name: redis1
        expose: 
            - "6379"
        ports: 
            - "6379:6379"
    portal-app: # The shiny application to rule them all 
        image: portal_app # Build 
        # container_name: portalapp1
        volumes:
            - "./cfg/minio_config.yml:/srv/shiny-server/cfg/minio_config.yml" # App needs to connect to minio
        ports:
            - "8300:8300"
        environment:
            - SHINYPROXY_USERNAME=test_user # Required to create folder in minio
    filterdata-app: # Demo container for filtering and plotting the iris dataset
        image: filter_app # Build 
        # container_name: filterdata1
        volumes:
            - "./cfg/minio_config.yml:/srv/shiny-server/cfg/minio_config.yml" # App needs to connect to minio
            - "./cfg/redis_config.yml:/srv/shiny-server/cfg/redis_config.yml" # App needs to connect to redis
            - "./FilterData-App/app.R:/srv/shiny-server/app.R"
        ports:
            - "4200:4200"
        environment:
            - SHINYPROXY_USERNAME=test_user # Required to create folder in minio
    filterdata-service:
        image: filter_service # Build 
        # container_name: filterservice1
        volumes:
            - "./cfg/minio_config.yml:/cfg/minio_config.yml" # Service needs to connect to minio
            - "./cfg/redis_config.yml:/cfg/redis_config.yml" # Service needs to connect to redis
            - "./FilterData-Service/rworker.R:/rworker.R"
        environment:
            - SHINYPROXY_USERNAME=test_user
        ports:
            - "4201:3838"


